# Generated by Django 3.2.9 on 2021-12-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_emailsended'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendEmailTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_task', models.UUIDField(unique=True, verbose_name='ID')),
                ('status', models.CharField(max_length=15, verbose_name='Status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
        ),
    ]
