# Generated by Django 3.2.9 on 2021-12-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_sendemailtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails', models.JSONField(default=[], verbose_name='List of emails')),
            ],
        ),
        migrations.DeleteModel(
            name='EmailSended',
        ),
        migrations.DeleteModel(
            name='SendEmailTask',
        ),
    ]
