# Generated by Django 3.2.9 on 2021-12-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_auto_20211213_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillist',
            name='emails',
            field=models.JSONField(default=list, verbose_name='List of emails'),
        ),
    ]
